name: whale-id
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alembic=1.6.4
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2021.5.25
  - cachetools=4.2.2
  - certifi=2021.5.30
  - certipy=0.1.3
  - cffi=1.14.5
  - chardet=3.0.4
  - click=8.0.1
  - colorama=0.4.4
  - configurable-http-proxy=4.0.1
  - coverage=5.5
  - cryptography=3.4.7
  - cycler=0.10.0
  - cython=0.29.23
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - gast=0.4.0
  - google-auth=1.30.1
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - greenlet=1.1.0
  - grpcio=1.36.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=3.0.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyter_telemetry=0.1.0
  - jupyterhub=1.3.0
  - jupyterhub-base=1.3.0
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.18.2
  - libcurl=7.71.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mako=1.1.4
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - nodejs=14.8.0
  - notebook=6.4.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - packaging=20.9
  - pamela=1.0.0
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - protobuf=3.14.0
  - psutil=5.8.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pygments=2.9.0
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python-json-logger=2.0.1
  - pytz=2021.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - ruamel.yaml=0.16.12
  - ruamel.yaml.clib=0.2.2
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sniffio=1.2.0
  - sqlalchemy=1.4.15
  - sqlite=3.35.4
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.5.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xz=5.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
